### PR TITLE
Giving some public credit to contributors, etc

### PR DESCRIPTION
**Pull request by csabapalfi**
Just wanted to give some public credit to contributors: @pgte @frederik256

Did I miss anyone else? Also let me know if you're happy with the wording :smile:

### CODE REVIEW

**Comment by csabapalfi** [comment]
Added @hassy and @joaojeronimo and also added a contributors section to package.json

**Comment by joaojeronimo** [comment]
I hardly contributed anything, add me when I make a PR ;)

**Comment by pgte** [comment]
LGTM

**Comment by csabapalfi** [comment]
@joaojeronimo still, you made some contributions, right?

**Comment by frederik256** [comment]
I didn't come up with the term/concept of the Warren, that's from RabbitMQ in Action by Videla & Williams - their warren is an Active/Passive approach fronted by a loadbalancer. That has some issues in it's own right, so I evolved the concept into this particular Active-Active loadbalancer free variation.

**Comment by csabapalfi** [comment]
@frederik256 ok, thanks for the clarification. I updated this in the README, too.

**Pull request merged**
